### ISSUE TITLE
Build Aborted.

### ISSUE THREAD

**Issue by ElMoha943** [Guribo/UdonVoiceUtils#10]
Hi i get an error when building the scene:
![imagen](https://user-images.githubusercontent.com/25410859/216540212-85b23520-91d7-40d6-b63d-eed1bc98f596.png)
![imagen](https://user-images.githubusercontent.com/25410859/216540521-e88604a9-4f29-430c-847a-bece2f69db4c.png)

Step to reproduce:
- Import package
- Add **ANY** prefab to the scene
- Build the project

I tried reimporting the pack already, also made sure that all references where there and even double checked with a friends project.

**Comment by ElMoha943** [comment]
I may add that the error also popups when going into playmode, and after it aborts all references of the betterplayeraudiocontroler are empty.

**Comment by Guribo** [comment]
I am looking into it, thanks! As a side note: this version is very outdated so I may just provide the latest version soon and update the repository ;)

**Comment by Guribo** [comment]
You may have to recompile your scripts manually and also check your console for errors. It may not be related to my unity package. Go to any GameObject with an UdonSharp script on it and click on recompile all:  

![image](https://user-images.githubusercontent.com/49484893/216722124-e1ded0d0-c741-4f29-b3ed-2760a3493357.png)



# I could not reproduce the issue. Here is what I did:

1. Using the Companion I created a new UdonSharpProject:     
   ![image](https://user-images.githubusercontent.com/49484893/216719035-bacf2542-cd1a-4c1f-93af-efa38d9f7072.png)
   
   ![image](https://user-images.githubusercontent.com/49484893/216719104-ee4d473c-c00b-4c99-978b-7052ed2baadb.png)

2. I added no extra packages and just opened it and wait for everything from VRChat to import:  
   
   ![image](https://user-images.githubusercontent.com/49484893/216719368-550b9865-63ab-4ca1-a4d6-c1a1d1755ec2.png)

   These are the packages currently available by the way:
   
   ![image](https://user-images.githubusercontent.com/49484893/216719642-be71917e-f786-4afa-94ca-fd667245787f.png)  
   ![image](https://user-images.githubusercontent.com/49484893/216719681-5839f81c-ee19-4fd8-8d6f-d7148561f93d.png)

3. I got greated with an empty project:     
   ![image](https://user-images.githubusercontent.com/49484893/216719882-64b138ac-7533-421b-ac0d-3e162e8dd85f.png)
4. I imported the latest unitypackage https://github.com/Guribo/UdonVoiceUtils/releases/tag/BPAv0.8 :  
   ![image](https://user-images.githubusercontent.com/49484893/216720094-66a8d1ae-c275-4679-a6ec-5496bcb6f094.png)
   
   ![image](https://user-images.githubusercontent.com/49484893/216720148-bc80b354-f2fb-4a27-bf3a-d710600d3083.png)
5. There was 2 prefab errors on the console, these are not really an issue though.
   
   ![image](https://user-images.githubusercontent.com/49484893/216720422-0b9636bb-74de-4d7d-8695-56294b575358.png)

6. I imported the TMP essentials and closed the TMP Importer window afterwards:  
   
   ![image](https://user-images.githubusercontent.com/49484893/216720537-2a3d8680-6551-42ed-8468-45fe5b504873.png)

7. Lastly I opened the example scene that comes with the unity package:
   
   ![image](https://user-images.githubusercontent.com/49484893/216720704-545e7fe6-33d4-47d0-a913-42ba90cf57a0.png)
8. The scene opened and is marked with an asterisk, indicating that something got changed. I just save the scene:  
   
   ![image](https://user-images.githubusercontent.com/49484893/216720867-9b8bd7b3-21ac-41b9-bbd8-7362a3e8f4eb.png)  
   ![image](https://user-images.githubusercontent.com/49484893/216720945-efbe58b9-758e-44f1-9b1e-de67a764a01a.png)

9. I clear the console:
   
   ![image](https://user-images.githubusercontent.com/49484893/216721065-1b775a17-575e-4a86-b10a-48be209ffc3c.png)
10. And finally log into my account and click Build & Test:
    
    ![image](https://user-images.githubusercontent.com/49484893/216721406-2a8d313e-28ec-4d83-94e7-87bda10a03bf.png)


All I see now is Unity building the scene and 3 instances of VRChat starting...

![image](https://user-images.githubusercontent.com/49484893/216721529-67a13b84-c953-472c-acf1-4009b54f2a55.png)  

Everything works as expected too.

![image](https://user-images.githubusercontent.com/49484893/216721739-29ab7dc2-c04b-47d6-8b93-ebf1d21f12dc.png)

**Hope this gives you an idea**

**Comment by Guribo** [comment]
I also tested the way you described now and now I can confirm it gives the error :(

1. created new Scene with floor and World descriptor:
   ![image](https://user-images.githubusercontent.com/49484893/216723346-b23f03e3-a7b6-495d-b250-b9fd85d58b19.png)

2. Added main prefab and a Microphone:
   
   ![image](https://user-images.githubusercontent.com/49484893/216723505-c5282769-f58d-4728-8f53-791b93b9ef62.png)
3. I saved the scene and again clicked on Build & Test:
   ![image](https://user-images.githubusercontent.com/49484893/216723646-3482e310-e0b7-455d-aef7-46b99924c741.png)
4. Error occurs:
   
   ![image](https://user-images.githubusercontent.com/49484893/216723850-1aea4087-4e73-4cc7-8597-93da1e4c2ba3.png)

**Comment by ElMoha943** [comment]
Hi there, i was able to fix it but tbh i dont even know how. I may wait for you to update to lastest version.

**Comment by Guribo** [comment]
To fix it I tried to unack the prefabs:

![image](https://user-images.githubusercontent.com/49484893/216724140-48f50d51-4b1a-4757-bcfa-c16d18bbe1b4.png)

and I clicked Recompile all a few times and I set all references to UdonCommon, UdonMath, UdonDebug and BetterPlayerAudio manually:

![image](https://user-images.githubusercontent.com/49484893/216724564-e0105ec4-fdc1-4559-9b48-04cda70d3213.png)
![image](https://user-images.githubusercontent.com/49484893/216724579-a4f4f234-3d5e-419b-98c5-923fd6a86c79.png)

I clicked save scene again and also recompile all, followed by one more save scene.

Now it builds and I can test the scene:

![image](https://user-images.githubusercontent.com/49484893/216724739-7fb29089-4feb-4750-ab83-f14dfa7c82da.png)

**Comment by Guribo** [comment]
You can get it work that way but that is obviously not want I want the workflow to be. 
I can't give a date though when the new version releases, I will try to get this done soon. Hope you understand.

**Comment by Guribo** [comment]
I will leave this ticket open until I uploaded the new version.

**Comment by ElMoha943** [comment]
I can confirm that setting everything a few times and saving the scene fixes it.

**Comment by Guribo** [comment]
[TLP.UdonVoiceUtils_PreRelease_v1.0.0_RC1.unitypackage.zip](https://github.com/Guribo/UdonVoiceUtils/files/12567039/TLP.UdonVoiceUtils_PreRelease_v1.0.0_RC1.unitypackage.zip)
this is the new version that I intend to release soon.

Make sure to make a backup of your project first
remove the Guribo folder if you have it in your project
import
restart Unity (it will complain about compiler errors otherwise which is a false positive)
check the demo scene: Packages/tlp.udonvoiceutils/Runtime/Scenes/PrivateZones/PrivateZones.unity

My Utilities and the Audio stuff has moved to the Packages folder, all of my stuff can be found int TLP.* folders

**Comment by ElMoha943** [comment]
Hi there, its been a long time. I ended up coding my own solution actually, but i will make sure to test your version on a map and report any bugs i encounter, thanx for your work!
