### ISSUE TITLE
scripting errors on import

### ISSUE THREAD

**Issue by Gab-Bryan** [Guribo/UdonVoiceUtils#18]
When I try to import the .unitypackage or the zipped folder to my VRchat world, there is a lot of scripts that are having errors with these kinds of descriptions : 

The type or namespace name 'View' 'Pool' 'UdonEvent' etc... could not be found (are you missing a using directive or an assembly reference?)
'PlayerAudioController.OnEvent(string)': no suitable method found to override

![issues](https://github.com/Guribo/UdonVoiceUtils/assets/56608487/071185fd-7a0e-441f-9b02-08f6973dab73)

**To Reproduce**
1. Download the latest unitypackage from https://Guribo.github.io/TLP/index.json
2. Extract the files into the world directory
3. Simply open your project and watch the console telling which errors are making the scripts unable to compile

**Expected behavior**
Apparently, everything should be fine.

**Plattform:**
 - [Windows 10] Desktop

**Additional context**
I tried using the Unity 2019 version and 2022 version. None of them worked properly

**Comment by Guribo** [comment]
You are missing some dependencies. Please don't try to use the unity package directly but install via VCC: https://guribo.github.io/TLP/

**Comment by Gab-Bryan** [comment]
I actually tried to do it via the VCC, but unfortunately it gives me as much errors as the manual download : 
![VCC errors](https://github.com/Guribo/UdonVoiceUtils/assets/56608487/ef1150ae-e0fd-4183-950e-619bd2f71372)

**Comment by Guribo** [comment]
Forgot that CyanObjectPool is something you need to add manually. Sorry: https://cyanlaser.github.io/CyanPlayerObjectPool/

**Comment by Gab-Bryan** [comment]
Oh thanks a lot!! its working perfectly fine now. Sorry I missed the second asset that I needed to add
