### ISSUE TITLE
U# does not yet support hiding base methods

### ISSUE THREAD

**Issue by ElMoha943** [Guribo/UdonVoiceUtils#20]
Upon updating to last version I'm getting this error:

![image](https://github.com/Guribo/UdonVoiceUtils/assets/25410859/525cff24-8210-4083-a685-f60b03611f63)

**Comment by ElMoha943** [comment]
i fixed it by removing the "Private" from Start(). it also happens con VoiceOverrideDoor, VoiceRangeVisualizer, PickUpMicrophone, etc

**Comment by Guribo** [comment]
You updated UdonUtils to a not yet supported version I assume. The companion should have given you a warning. Make sure you use UdonUtils 2.0.0.
