### ISSUE TITLE
World listing request

### ISSUE THREAD

**Issue by sleahymusic** [Guribo/UdonVoiceUtils#22]
[comment]: # (Please note you must be the owner/creator of the world or the world must contain information about using UVU, this measure is to prevent worlds from being listed that don't actually use UVU)
1. **World name:** `Virtual Performing Arts Theater`

[comment]: # (World ID is optional, if added you consent to a portal to this world potentially being added in a tutorial world)
2. **World ID:** `(https://vrchat.com/home/world/wrld_f1ae5929-a881-4c21-acc0-8d5cb9bf919f)`

[comment]: # (Your name is optional, if not provided the VRChat user name of the player owning the world will be used)
3. **Your name to be displayed:** `DjembeDragon`

**Comment by Guribo** [comment]
Nice world! May I ask how/where it is used (e.g. which features)? I assume something on the stage?

**Comment by sleahymusic** [comment]
Good morning!  We use your scripts all OVER the world!  We have a special zone for the Audience which we've scripted with controls so that staff can change the audience live during the show if they are loud and mute them, or lower them... we have scripts to control the stage volume and far also on the fly, we use a reverb effect that we can turn on and off for during the performances, we use two private channels for communication between back stage and the control room on the third floor, and also another channel to speak to the green room to prepare the artist for their entry.  I think thats all lol... it's been essential to what we do there!  Thank you!  I was wondering one thing though.  Is is possible to channel audio sources to specific channels as well?

    On Saturday, May 11, 2024 at 07:27:52 AM EDT, Guribo ***@***.***> wrote:   

 


Nice world! May I ask how/where it is used (e.g. which features)? I assume something on the stage?

**Comment by Guribo** [comment]
Thanks for the detailed response! This seems to be the most advanced setup I have seen so far =)

I will update the list when i am back from vacation.

Regarding audio sources in private channels: this is not implemented but it sounds like a nice addition so I will think about how that can be implemented. Thank you for the idea!

**Comment by sleahymusic** [comment]
Excellent!   Please let me know if you figure that out! 

Sent from AOL on Android 
 
  On Sat, May 11, 2024 at 10:35 AM, ***@***.***> wrote:   


Thanks for the detailed response! This seems to be the most advanced setup I have seen so far =)

I will update the list when i am back from vacation.

Regarding audio sources in private channels: this is not implemented but it sounds like a nice addition so I will think about how that can be implemented. Thank you for the idea!

**Comment by sleahymusic** [comment]
I really wish there were a way to turn reverb on for just the stage but so that everyone hears the reverb of the person on stage without everyone having reverb but I know that's not functional at least now in VRChat.  Also it would be cool if players could hear their own echo like in a cave when they speak.  
    On Saturday, May 11, 2024 at 10:35:44 AM EDT, Guribo ***@***.***> wrote:   

 


Thanks for the detailed response! This seems to be the most advanced setup I have seen so far =)

I will update the list when i am back from vacation.

Regarding audio sources in private channels: this is not implemented but it sounds like a nice addition so I will think about how that can be implemented. Thank you for the idea!

**Comment by Guribo** [comment]
I added the world to the list, please check if it is OK like this (you can close this issue afterward or I will do it). I also added a new issue to track that idea of yours:

Listing: https://github.com/Guribo/UdonVoiceUtils?tab=readme-ov-file#where-is-it-being-used
Feature Request: https://github.com/Guribo/UdonVoiceUtils/issues/23

**Comment by sleahymusic** [comment]
Thank you that is awesome!   Thanks for all you do! 

Sent from AOL on Android 
 
  On Sun, May 12, 2024 at 7:32 PM, ***@***.***> wrote:   


I added the world to the list, please check if it is OK like this (you can close this issue afterward or I will do it). I also added a new issue to track that idea of yours:

Listing: https://github.com/Guribo/UdonVoiceUtils?tab=readme-ov-file#where-is-it-being-used
Feature Request: #23
